# Generated by Django 5.0 on 2023-12-07 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seats', models.PositiveIntegerField()),
                ('screen_size', models.CharField(choices=[('Standard', 'Standard'), ('Large', 'Large'), ('Premium', 'Premium')], default='Standard')),
                ('screen_type', models.CharField(choices=[('2D', '2D Screen'), ('3D', '3D Screen')], default='2D', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_in_minutes', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=128)),
                ('poster', models.ImageField(blank=True, default='static/img/movie_poster.jpg', max_length=255, null=True, upload_to='movie_images/')),
            ],
        ),
        migrations.CreateModel(
            name='MovieShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('sold_seats', models.PositiveIntegerField(default=0)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie_shows.movie')),
                ('movie_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movie_shows.cinemahall')),
            ],
        ),
    ]
