# Generated by Django 4.2 on 2023-12-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_shows', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seat_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
