# Generated by Django 4.2 on 2023-12-25 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_shows', '0005_alter_cinemahall_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieshow',
            options={},
        ),
    ]
