# Generated by Django 4.2 on 2023-12-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_order_ordered_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
