# Generated by Django 4.2 on 2023-12-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
